### ISSUE TITLE
Bitcoin-QT Can't Access System Volume Information

### ISSUE THREAD

**Issue by Linrono** [bitcoin-core/gui#99] opened 2020-09-28 04:09 UTC
I have the C:\Users\username\AppData\Roaming\Bitcoin folder as a soft link to a separate internal drive. This apparently caused an issue when trying to access another wallet. NTFS has created a hidden folder called System Volume Information on the root of the drive where the data directory is. When I try to open another wallet inside of Bitcoin-QT, it freezes up. The error I get in the log is ListWalletDir: Access is denied C:\Users\Linrono\AppData\Roaming\Bitcoin\System Volume Information. This shows up in the logs over and over until I force close Bitcoin-QT. It took up my entire 10MB log file at one point. An easy fix for me would be to just create a folder in the volume and move my soft link to point there. I just wanted to bring this to your attention.

**Expected behavior**

I thought I would get a list of wallets I have created in the directory with the createwallet command.

**Actual behavior**

This caused a freeze that required the program to be force closed.

**To reproduce**

It has happened to me every time I go to File and then mouse over Open Wallet.

**System information**

I am using Bitcoin Core v.20.1 from the BitcoinCore.org website.

Windows 10, Ryzen 5, Hard Drive

I believe this issue is related to the NTFS system folder on the root of volumes.

ListWalletDir: Access is denied C:\Users\Linrono\AppData\Roaming\Bitcoin\System Volume Information

**Comment by MarcoFalke** [comment] 2020-09-28 06:23
This is probably also reproducible in bitcoind.exe, since it is the wallet behavior, I think

**Comment by Linrono** [comment] 2020-10-02 01:43
I was able to recreate the error with bitcoind. Should I open a ticket on the main git?

**Comment by MarcoFalke** [comment] 2020-10-02 06:50
Yes, please. I remember we had a similar issue, but I can't find it.

**Comment by prusnak** [comment] 2021-01-19 15:33
This should be closed in favor of https://github.com/bitcoin/bitcoin/issues/20081

**Closed** 2021-01-19 15:52 UTC
Labels: Bug
