### ISSUE TITLE
Control changes from clickable to unclickable upon canceling.

### ISSUE THREAD

**Issue by katesalazar** [bitcoin-core/gui#392] opened 2021-08-02 13:32 UTC
Load a wallet, "Settings" > "Encrypt Wallet..." can be clicked. Click it, modal opens, cancel modal, now "Settings" > "Encrypt Wallet..." cannot be clicked ("disabled grey").

**Expected behavior**

The control being disabled from the beginning.

**Actual behavior**

Control started clickable and idempotence not happening until after having clicked the control.

**To reproduce**

Open Bitcoin GUI, load the wallet (if not loaded). Close Bitcoin GUI. Open it again so that it loads the wallet automatically. Reproduce. After closing the wallet, the issue doesn't happen anymore by reloading the wallet, until closing Bitcoin GUI and launching it again.

**System information**

This is v22.0rc1 built from sources, but I can check master and previous tags as necessary. I'd say the 0.21.1 tag is free from this behavior.

This is Debian Buster (10) right on top of the amd64 metal.

Qt reports 5.11.3, Plasma is 5.14.5 (I think).

I'd be bisecting this soon.

**Comment by hebasto** [comment] 2021-08-03 12:53
@katesalazar 

Thank you for your report!

Tested 22.0rc1, 22.0rc2 and master on Linux Mint 20.2 (Qt 5.12.8) -- cannot reproduce the bug you described.
Wallet details: the only wallet is loaded automatically during the GUI startup.

Will test on other systems.

**Comment by katesalazar** [comment] 2021-08-03 16:21
I finally ended running git bisect, reaching https://github.com/bitcoin-core/gui/commit/20e2e24e90. 🤔

**Comment by katesalazar** [comment] 2021-08-03 16:33
I had been using a production wallet for this.

I just created and encrypted an empty wallet, and the same thing is happening
to it. When trying to force the way to encrypt the encrypted empty wallet
it's showing this modal:

"Wallet encryption failed"
"Wallet encryption failed due to an internal error. Your wallet was not
encrypted."
"[ OK ]"

**Comment by hebasto** [comment] 2021-08-03 16:42
I misread the issue description.

I can confirm this bug with _encrypted_ wallet.

**Comment by hebasto** [comment] 2021-08-03 19:31
@katesalazar 

Fixed in #393. Do you mind testing it?

**Comment by katesalazar** [comment] 2021-08-03 19:38
I think bringing back line

    connect(walletView, &WalletView::encryptionStatusChanged, gui, &BitcoinGUI::updateWalletStatus);

 of https://github.com/bitcoin/bitcoin/commit/20e2e24e90 removes the issue. But I don't understand the implications and how that fits with the rest of that refactoring.

**Comment by hebasto** [comment] 2021-08-03 19:51
> I think bringing back line
> 
> ```
> connect(walletView, &WalletView::encryptionStatusChanged, gui, &BitcoinGUI::updateWalletStatus);
> ```
> 
> of [bitcoin/bitcoin@20e2e24](https://github.com/bitcoin/bitcoin/commit/20e2e24e90) removes the issue. But I don't understand the implications and how that fits with the rest of that refactoring.

You are right. In #393 I just try to keep all `connect` calls grouped.

**Comment by katesalazar** [comment] 2021-08-03 20:26
> @katesalazar
> 
> Fixed in #393. Do you mind testing it?

I tested it and the bug was gone.

Then just to be sure I reverted it and the bug was back as expected.

**Comment by hebasto** [comment] 2021-08-03 20:59
@katesalazar
> I tested it and the bug was gone.
> 
> Then just to be sure I reverted it and the bug was back as expected.

Thanks for testing!

Could you leave a comment in https://github.com/bitcoin-core/gui/pull/393?

**Comment by jarolrod** [comment] 2021-08-05 04:29
Confirming this bug on master

**Closed** 2021-08-05 06:49 UTC
Labels: Bug, UX, Wallet
