### ISSUE TITLE
commit ecb617fefe drops qt/gui support on MacOS 10.15.7

### ISSUE THREAD

**Issue by RandyMcMillan** [bitcoin-core/gui#760] opened 2023-09-22 17:44 UTC
Commit ecb617fefe9fbd15365dcf0469d4d39df6b856bc bumps qt version to 5.15.5

This arbitrarily drops qt gui building on  MacOS 10.15.7

A patch may be useful to maintain building/testing on MacOS 10.15.7
Note that qt@6 runs on MacOS 10.15.7 so extending support for MacOS 10.15.7
seems reasonable.

```
git blame depends/packages/qt.mk
```

```
c870027cc2 (fanquake               2020-07-29 18:29:58 +0800   1) package=qt
ecb617fefe (Hennadii Stepanov      2022-07-26 12:42:37 +0100   2) $(package)_version=5.15.5
c870027cc2 (fanquake               2020-07-29 18:29:58 +0800   3) $(package)_download_path=https://download.qt.io/official_releases/qt/5.15/$($(package)_version)/submodules
ef20add4c9 (Pavol Rusnak           2022-03-25 10:32:32 +0100   4) $(package)_suffix=everywhere-opensource-src-$($(package)_version).tar.xz
```

```
git show ecb617fefe9fbd15365dcf0469d4d39df6b856bc
```

```
diff --git a/depends/packages/qt.mk b/depends/packages/qt.mk
index bddc9b487..a23682956 100644
--- a/depends/packages/qt.mk
+++ b/depends/packages/qt.mk
@@ -1,9 +1,9 @@
 package=qt
-$(package)_version=5.15.3
+$(package)_version=5.15.5
 $(package)_download_path=https://download.qt.io/official_releases/qt/5.15/$($(package)_version)/submodules
 $(package)_suffix=everywhere-opensource-src-$($(package)_version).tar.xz
 $(package)_file_name=qtbase-$($(package)_suffix)
-$(package)_sha256_hash=26394ec9375d52c1592bd7b689b1619c6b8dbe9b6f91fdd5c355589787f3a0b6
+$(package)_sha256_hash=0c42c799aa7c89e479a07c451bf5a301e291266ba789e81afc18f95049524edc
 $(package)_linux_dependencies=freetype fontconfig libxcb libxkbcommon libxcb_util libxcb_util_render libxcb_util_keysyms libxcb_util_image libxcb_util_wm
 $(package)_qt_libs=corelib network widgets gui plugins testlib
 $(package)_linguist_tools = lrelease lupdate lconvert
@@ -17,17 +17,16 @@ $(package)_patches += fix_montery_include.patch
 $(package)_patches += fix_android_jni_static.patch
 $(package)_patches += dont_hardcode_pwd.patch
```

**Comment by hebasto** [comment] 2023-09-22 18:03
The self-building of Bitcoin Core GUI on macOS relies on Homebrew package manager, which provides the [`qt@5`](https://formulae.brew.sh/formula/qt@5) package for macOS 11 Big Sur and newer OS versions.

Moreover, macOS 10.15 support has been dropped since https://github.com/bitcoin/bitcoin/pull/27676.

Users of older macOS versions can still use older compatible Bitcoin Core releases (with certain drawbacks, of course).

I don't think we can do anything meaningful here.

**Comment by hebasto** [comment] 2023-09-22 18:06
Going to close this issue.

If any further discussion seems needed, please reopen it in the main repository as it touches the build system.

**Closed by hebasto** 2023-09-22 18:06 UTC
Labels: macOS

**Comment by RandyMcMillan** [comment] 2023-09-22 19:45
This version of THE BITCOIN CLIENT actually builds fine on MacOS 10.15.7 with qt@5

https://github.com/bitcoincore-dev/bitcoin/tree/1695411519/6745e3693e/ce687d9903-macos/10.15.7/patch/delta

Seems more like extremely brittle build tooling to me...

**Comment by fanquake** [comment] 2023-09-23 17:24
> This arbitrarily drops qt gui building on MacOS 10.15.7

You didn't actually post what the issue is. What fails?

> The self-building of Bitcoin Core GUI on macOS relies on Homebrew package manager, 

No it doesn't? Depends should work fine.

**Comment by hebasto** [comment] 2023-09-23 17:26
> > The self-building of Bitcoin Core GUI on macOS relies on Homebrew package manager,
> 
> No it doesn't? Depends should work fine.

Indeed. Depends or Homebrew's packages.
